coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 10%
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
